server:
  port: 8100

spring:
  application:
    name: spring-gateway
  zipkin:
    #      base-url: http://localhost:9411/
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  #    web:
  #      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true # 开启通过服务中心的自动根据 serviceId 创建路由的功能
        default-filters:
          - My=true
        routes:
          - id: ribbon-route
            uri: lb://EUREKA-RIBBON
            order: 0
            predicates:
              - Path=/ribbon/**
            filters:
              - name: RequestRateLimiter
                args:
                  key-resolver: '#{@ipKeyResolver}'
                  redis-rate-limiter.replenishRate: 200
                  redis-rate-limiter.burstCapacity: 400
              - name: Hystrix
                args:
                  name: fallback
                  fallbackUri: forward:/fallback
              - StripPrefix=1 #去掉前缀，具体实现参考StripPrefixGatewayFilterFactory
              - AddResponseHeader=X-Response-Default-Foo, Default-Bar
              - name: Retry
                args:
                  retries: 3
                  series:
                    - SERVER_ERROR
                  statuses:
                    - OK
                  method:
                    - GET
                    - POST
                  exceptions:
                    - java.io.IOException
          - id: feign-route
            uri: lb://EUREKA-FEIGN
            order: 0
            predicates:
              - Path=/feign/**
            filters:
              - StripPrefix=1
              - AddResponseHeader=X-Response-Default-Foo, Default-Bar


eureka:
  instance:
    hostname: eureka1.server.com
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 5
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    # 默认为90秒
    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    # 该值至少应该大于 leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka1.server.com:8701/eureka/,http://eureka2.server.com:8702/eureka/,http://eureka3.server.com:8703/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
